easy_admin:
  design:
    brand_color: 'blue'

  entities:
    Formation:
      class: App\Entity\Formation
      label: 'Formation'
      list:
        actions:
          - { name: 'en_ligne', type: 'custom', label: 'Mettre en ligne', icon: 'check'}

    Homepage:
      class: App\Entity\Homepage
      label: 'Accueil'
      list:
        actions:
          - { name: 'en_ligne', type: 'custom', label: 'Mettre en ligne', icon: 'check'}

    Presentation:
      class: App\Entity\Presentation
      label: 'Informations'
      list:
        actions:
          - { name: 'en_ligne', type: 'custom', label: 'Mettre en ligne', icon: 'check'}
