easy_admin:
  entities:

    Presentation:
      class: App\Entity\Presentation
      controller: App\Controller\Admin\Presentation_page\PresentationCrudController
      label: 'Page présentation'

    Formation:
      class: App\Entity\Formation
      label: 'Formation'
      list:
        actions:
          - { name: 'en_ligne', type: 'custom', label: 'Mettre en ligne', icon: 'check'}

    Homepage:
      class: App\Entity\Homepage
      label: 'Accueil'
      list:
        actions:
          - { name: 'en_ligne', type: 'custom', label: 'Mettre en ligne', icon: 'check'}
