vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
